"""Public operator-workflow contracts for embodied systems."""

from ._version import __version__
from .artifacts import (
    OutputDirectoryTransaction,
    PublishedOutputCleanupError,
    atomic_output_directory,
    atomic_output_file,
    atomic_write_json,
    atomic_write_text,
    create_only_output_file,
    directory_sha256,
    file_sha256,
    read_json_object,
    read_jsonl_objects,
    write_json_once,
    write_text_once,
)
from .artifact_store import (
    ArtifactValidation,
    fetch_huggingface_artifact,
    validate_artifact,
)
from .collection import (
    CollectionInteraction,
    CollectionResetPolicy,
    EpisodeDecision,
    LeadingStillnessConfig,
    LeadingStillnessResult,
    LeadingStillnessTrimmer,
    STANDARD_COLLECTION_INTERACTION,
    TimedSample,
    normalize_collection_start,
    normalize_episode_decision,
    require_fresh_sample,
    require_pair_skew,
    reset_required_after_episode,
    validate_experiment_name,
)
from .collection_presentation import (
    EpisodeCaptureReport,
    announce_collection_session,
    announce_collection_summary,
    announce_episode_capture,
    announce_episode_outcome,
)
from .code_environment import (
    ensure_code_checkout,
    ensure_code_environment,
    verify_code_checkout,
    verify_code_environment,
    verify_environment_lock,
)
from .contracts import add_contract_digest, validate_exact_metadata
from .task_selection import TaskSelectionCancelled, select_task
from .evaluation import (
    EvaluationPlan,
    EvaluationProgress,
    EvaluationSlot,
    summarize_evaluation_progress,
    validate_identifier,
)
from .task_registry import (
    TaskCatalog,
    TaskDistribution,
    TaskPrompt,
    load_task_catalog,
    register_task_prompt,
)
from .presentation import (
    CheckResult,
    checks_exit_code,
    checks_payload,
    checks_to_json,
    finish_checks,
    print_checks,
    print_dataset_report,
    print_export_report,
    standard_dataset_report,
    standard_export_report,
)

__all__ = [
    "ArtifactValidation",
    "CollectionInteraction",
    "CollectionResetPolicy",
    "CheckResult",
    "EpisodeDecision",
    "EpisodeCaptureReport",
    "EvaluationPlan",
    "EvaluationProgress",
    "EvaluationSlot",
    "LeadingStillnessConfig",
    "LeadingStillnessResult",
    "LeadingStillnessTrimmer",
    "OutputDirectoryTransaction",
    "PublishedOutputCleanupError",
    "STANDARD_COLLECTION_INTERACTION",
    "TimedSample",
    "TaskCatalog",
    "TaskDistribution",
    "TaskPrompt",
    "TaskSelectionCancelled",
    "__version__",
    "add_contract_digest",
    "atomic_output_directory",
    "atomic_output_file",
    "atomic_write_json",
    "atomic_write_text",
    "create_only_output_file",
    "directory_sha256",
    "ensure_code_checkout",
    "ensure_code_environment",
    "file_sha256",
    "fetch_huggingface_artifact",
    "load_task_catalog",
    "normalize_collection_start",
    "normalize_episode_decision",
    "read_json_object",
    "read_jsonl_objects",
    "register_task_prompt",
    "announce_collection_session",
    "announce_collection_summary",
    "announce_episode_capture",
    "announce_episode_outcome",
    "checks_exit_code",
    "checks_payload",
    "checks_to_json",
    "finish_checks",
    "print_checks",
    "print_dataset_report",
    "print_export_report",
    "require_fresh_sample",
    "require_pair_skew",
    "reset_required_after_episode",
    "select_task",
    "standard_dataset_report",
    "standard_export_report",
    "summarize_evaluation_progress",
    "validate_experiment_name",
    "validate_identifier",
    "validate_exact_metadata",
    "validate_artifact",
    "verify_code_checkout",
    "verify_code_environment",
    "verify_environment_lock",
    "write_json_once",
    "write_text_once",
]
